# Generated by Django 2.2.2 on 2019-11-24 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_bank',
            name='A',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='AB',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='AB_mi',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='A_mi',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='B',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='B_mi',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='O',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='O_mi',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 6, 11, 9, 573977, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Bloodtype',
        ),
    ]
