# Generated by Django 2.2.2 on 2019-11-24 06:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbank', '0002_auto_20191124_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank',
            name='A',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='AB',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='AB_mi',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='A_mi',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='B',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='B_mi',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='O',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='O_mi',
            field=models.IntegerField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 6, 16, 41, 585752, tzinfo=utc)),
        ),
    ]
