# Generated by Django 2.2.2 on 2019-11-28 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbank', '0003_auto_20191124_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='u_id',
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 5, 47, 53, 660852, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='LastDonated',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
