# Generated by Django 2.2.2 on 2019-11-29 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbank', '0005_auto_20191128_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Email',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 8, 49, 48, 77838, tzinfo=utc)),
        ),
    ]
