# Generated by Django 2.2.2 on 2019-11-29 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbank', '0006_auto_20191129_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 8, 50, 49, 602748, tzinfo=utc)),
        ),
    ]
